// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/scalent-io/shiprocket/pkg"
)

// Injectors from wire.go:

func initServer() (*ShiprocketClient, error) {
	shiprocketServiceImpl, err := pkg.NewShiprocketServiceImpl()
	if err != nil {
		return nil, err
	}
	dependencyOptions := DependencyOptions{
		ShiprocketService: shiprocketServiceImpl,
	}
	shiprocketClient := NewShiprocketClient(dependencyOptions)
	return shiprocketClient, nil
}

// wire.go:

var ModuleSet = wire.NewSet(wire.Struct(new(DependencyOptions), "*"), NewShiprocketClient, pkg.NewShiprocketServiceImpl, wire.Bind(new(pkg.ShiprockertService), new(*pkg.ShiprocketServiceImpl)))
